tag: v1.0.14

file:
  - name: 1.yaml
    keys:
      key1: value_1x1
      key2: value_y
      key3:
        key31:
          key311: value_z
  - name: 2.yaml
    keys:
      key1: value_aa
      key2: value_bb


